### ISSUE TITLE
Adding to quicklisp

### ISSUE THREAD

**Issue by cage2** [mmontone/sxql-composer#1]
Hello!

This library seems useful, i wonder why is not in quicklisp. The addition of this code to the repository would make my life easier! ;-)

Bye!
C.

**Comment by mmontone** [comment]
Ok. I'll ask for its inclusion.

**Comment by cage2** [comment]
On Sat, Mar 14, 2020 at 08:47:58AM -0700, Mariano Montone wrote:

Hi!

> Ok. I'll ask for its inclusion.

Thank you very much!

Bye!
C.

**Comment by mmontone** [comment]
It's been added

**Comment by cage2** [comment]
On Wed, Mar 25, 2020 at 11:12:00AM -0700, Mariano Montone wrote:
> It's been added

Fantastic! :)

Bye!
C.
